# Generated by Django 3.0.3 on 2020-02-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default='1'),
        ),
    ]
